# Array Creation Routine
---
- numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
- numpy.zeros(shape, dtype = float, order = 'C')
- numpy.ones(shape, dtype = None, order = 'C')
- numpy.empty(shape, dtype = float, order = 'C')
- numpy.full(shape, fill_value, dtype = None, order = 'C')
- numpy.arange(start = 0, stop, step = 1, dtype = None)
- numpy.linspace(start = 0, stop, num = 50, endpoint = True, retstep = False, dtype = None)
- numpy.logspace(start = 0, stop, num = 50, endpoint = True, base = 10, dtype = None)
- numpy.random.random(size = None)
- numpy.random.normal(loc = 0.0, scale = 1.0, size = None)
- numpy.random.randint(low, high = None, size = None, dtype = 'int')
---

##### loads numpy module

In [27]:
import numpy as np

##### create numpy arrary from list and tuple object

In [47]:
# list to ndarray

# sample list
sample = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# list to numpy object
print(np.array(sample))

# set data type float32
print(np.array(sample, dtype = 'float32'))

# check type
print(type(np.array(sample)))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [49]:
# tuple to ndarray

# sample tuple
sample = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# tuple to numpy object
print(np.array(sample))

# set data type float32
print(np.array(sample, dtype = 'float32'))

# check type
print(type(np.array(sample)))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
