# Array Creation Routine
---
- numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
- numpy.zeros(shape, dtype = float, order = 'C')
- numpy.ones(shape, dtype = None, order = 'C')
- numpy.empty(shape, dtype = float, order = 'C')
- numpy.full(shape, fill_value, dtype = None, order = 'C')
- numpy.arange(start = 0, stop, step = 1, dtype = None)
- numpy.linspace(start = 0, stop, num = 50, endpoint = True, retstep = False, dtype = None)
- numpy.logspace(start = 0, stop, num = 50, endpoint = True, base = 10, dtype = None)
- numpy.random.random(size = None)
- numpy.random.normal(loc = 0.0, scale = 1.0, size = None)
- numpy.random.randint(low, high = None, size = None, dtype = 'int')
---

#### loads numpy module

In [1]:
import numpy as np

#### create numpy arrary from list and tuple object - array

In [2]:
# list to ndarray

# sample list
sample = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# list to numpy array
print(np.array(sample), '\n')

# set data type float32
print(np.array(sample, dtype = 'float32'), '\n')

# check type
print(type(np.array(sample)), '\n')

[ 1  2  3  4  5  6  7  8  9 10] 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 

<class 'numpy.ndarray'> 



In [3]:
# tuple to ndarray

# sample tuple
sample = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# tuple to numpy array
print(np.array(sample), '\n')

# set data type float32
print(np.array(sample, dtype = 'float32'), '\n')

# check type
print(type(np.array(sample)), '\n')

[ 1  2  3  4  5  6  7  8  9 10] 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 

<class 'numpy.ndarray'> 



#### create numpy array - zeros, ones, empty, full

In [4]:
# create numpy array filled with zeros
print(np.zeros((2,3)), '\n') 

[[0. 0. 0.]
 [0. 0. 0.]] 



In [5]:
# create numpy array filled with ones
print(np.ones((3,2)), '\n')

[[1. 1.]
 [1. 1.]
 [1. 1.]] 



In [6]:
# create empty numpy array
print(np.empty((2,2)), '\n')

[[5.81135006e-312 2.50170012e+267]
 [1.99914751e+161 5.03734574e+180]] 



In [7]:
# create numpy array with speceific number
print(np.full((2,3), 20), '\n')

[[20 20 20]
 [20 20 20]] 



#### create numpy array from range - arange, linspace, logspace

In [8]:
# arnage
print(np.arange(1, 10), '\n')

# step = 2
print(np.arange(1, 10, 2), '\n')

[1 2 3 4 5 6 7 8 9] 

[1 3 5 7 9] 



In [9]:
# linspace

# num = 5
print(np.linspace(0, 100, 5), '\n')

# num = 10, endpoint = false
print(np.linspace(0, 100, 10, endpoint = False), '\n')

[  0.  25.  50.  75. 100.] 

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.] 



In [10]:
# logspace

# num = 5
print(np.logspace(0, 1, 5), '\n')

# base = 2
print(np.logspace(0, 1, 5, base = 2), '\n')

[ 1.          1.77827941  3.16227766  5.62341325 10.        ] 

[1.         1.18920712 1.41421356 1.68179283 2.        ] 



#### create numpy array from random number - random, normal, randint

In [11]:
# random.random

# set seed
np.random.seed(0)

# size = 5
print(np.random.random(5), '\n')

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ] 



In [12]:
# random.normal

# set seed
np.random.seed(0)

# mean = 0, std = 1, size = (2,3)
print(np.random.normal(0, 1, (2,3)), '\n')

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]] 



In [13]:
# random.randint

# set seed
np.random.seed(0)

# low_num = 1, high_num = 10, count = 10
print(np.random.randint(1, 10, 10), '\n')

# low_num = 1, high_num = 10, size = (2,3)
print(np.random.randint(1, 10, (2, 3)), '\n')

[6 1 4 4 8 4 6 3 5 8] 

[[7 9 9]
 [2 7 8]] 

