# Array Attribute

---

##### array attribute
- ndarray.ndim
- ndarray.shape
- ndarray.size
- ndarray.dtype
- ndarray.itemsize
- ndarray.nbytes

---

##### attribute related functions
- numpy.shape(array)
- ndarray.reshape(shape, order = 'C')
- numpy.reshape(array, shape, order = 'C')
- ndarray.resize(shape, refcheck = True)
- numpy.resize(array, shape)
---


(\* ndarray is numpy array object)

#### loads numpy module

In [1]:
import numpy as np

#### array attribute

In [2]:
sample = np.ones((2,3,4), dtype = 'i8')

# ndim => returns dimension
print("dimension: ", sample.ndim, '\n')

# shape => returns shape
print("shape: ", sample.shape, '\n')

# dtype => returns data type
print("data type: ", sample.dtype, '\n')

#itemsize => returns num of elements
print("item size: ", sample.itemsize, '\n')

# nbytes => returns total bytes
print("nbytes: ", sample.nbytes, '\n')

dimension:  3 

shape:  (2, 3, 4) 

data type:  int64 

item size:  8 

nbytes:  192 



#### attribute related functions

###### shape

In [3]:
# check shape

sample = np.ones((2,3,4))
print('shape: ', np.shape(sample), '\n')

shape:  (2, 3, 4) 



###### reshape

In [4]:
# reshape method 1 - ndarray.reshape

sample = np.ones((2,3,4))
print("pre shape: ", np.shape(sample), '\n')

sample_reshaped = sample.reshape((6,4))
print("reshaped shape: ", np.shape(sample_reshaped), '\n')

pre shape:  (2, 3, 4) 

reshaped shape:  (6, 4) 



In [5]:
# reshape method 2 - numpy.reshpae

sample = np.ones((2,3,4))
print("pre shape: ", np.shape(sample), '\n')

sample_reshaped = np.reshape(sample, (6,4))
print("reshaped shape: ", np.shape(sample_reshaped), '\n')

pre shape:  (2, 3, 4) 

reshaped shape:  (6, 4) 



In [6]:
# tips

# -1 means no consideration
sample = np.ones(5, dtype='i8')
print(sample, '\n')

sample2 = sample.reshape(-1, 1)
print(sample2, '\n')

[1 1 1 1 1] 

[[1]
 [1]
 [1]
 [1]
 [1]] 



###### resize

In [7]:
# resize method 1 - ndarray.resize
# return type is None !

sample = np.ones((2,3,4))
print("pre shape: ", sample.shape, '\n')

sample.resize((6,4))
print("resized shape: ", sample.shape, '\n')

pre shape:  (2, 3, 4) 

resized shape:  (6, 4) 



In [8]:
# resize method 2 - numpy.resize

sample = np.ones((2,3,4))
print("pre shape: ", sample.shape, '\n')

sample_reshaped = np.resize(sample, (6,4))
print("resized shape: ", sample_reshaped.shape, '\n')

pre shape:  (2, 3, 4) 

resized shape:  (6, 4) 



In [9]:
# reshape vs resize
# reshape method must fit pre shape and post shape
# resize method will fill array with specific num

sample = np.array([1,2,3,4,5,6])
print(sample, '\n')

sample2 = np.resize(sample, (2, 12))
print(sample2, '\n')

[1 2 3 4 5 6] 

[[1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]] 

